### ISSUE TITLE
Actualizar Dalle // Updating Dalle.

### ISSUE THREAD

**Issue by EuriNaiz** [albfernandez/dalle#1]
Estoy consciente que ésta herramienta fue creada hace aproximadamente diez años, si es que no, más, y por razones muy especificas, puesto que en el internet de la época era algo necesario, pero eso no significa que en la actualidad no tenga alguna utilidad, como por ejemplo en la esteganografía, el uso que yo por ejemplo le daría al programa y le doy a los comandos ```split``` y ```cat```. 

Entonces, abro este issue con el fin de siquiera conocer si existe la posibilidad de hacerle un update para que funcione en los sistemas actuales (al menos en GNU/Linux Debian Buster 10 ya no funciona (no se instala)).

```dalle : Depende: libgnome2.24-cil (>= 2.24.0) pero no es instalable```

Los comandos ```split``` y ```cat``` son útiles, claro, pero una herramienta gráfica es más cómoda, y en la seguridad (sobre todo en el cifrado y la esteganografía) es obligatorio el uso de herramientas libres.
Desconozco del lenguaje C#, así que no puedo hacerlo yo, pero qué mejor que el mismo creador (si es qué puedes y quieres hacerlo), aunque supongo que ha de ser relativamente sencillo siquiera hacerle una interfáz gráfica a los comandos ```split``` y ```cat```, aunque digo eso desde mi ignorancia, no sé programar todavía.

Me quedo a la espera de cualquier respuesta, y ¡Gracias!.

--- 

I am aware that this tool was created approximately ten years ago, if not, more, and for very specific reasons, since in the internet at the time it was something necessary, but that does not mean that at present it does not have any use, such as for example in steganography, the use that I for example would give to the program and I give the commands ```split``` and ```cat```.

So, I open this issue in order to even know if there is the possibility of making an update to it so that it works on current systems (at least on GNU / Linux Debian Buster 10 no longer works (it does not install)).

```dalle: Depends: libgnome2.24-cil (> = 2.24.0) but not installable```

The commands ```split``` and ```cat``` are useful, of course, but a graphical tool is more comfortable, and in security (especially in encryption and steganography) the use of tools is mandatory libre.
I'm not familiar with the C# language, so I can't do it myself, but what better than the creator himself (if you can and want to do it), although I suppose it must be relatively easy to even make a graphical interface to the ```split``` and ```cat``` commands, although I say that from my ignorance, I don't know how to program yet.

I am waiting for any response, and Thank you!

**Comment by albfernandez** [comment]
Hola

Muchas gracias por tus palabras de ánimo. Hace unos 18 años empecé el proyecto y lleva tiempo sin actualizar pero no sabía que no era compatible con las nuevas versiones de Debian/Ubuntu (como voy actualizando la misma instalación desde hace años aún tengo el paquete libgnome-2.4-cil instalado)

Probaré a compilarlo en versiones recientes de ubuntu y debian (en una instalación limpia) y haré una release, aunque con algo de calma
Un saludo.

**Comment by albfernandez** [comment]
Subido un nuevo deb  para Buster en la pagina de sourceforge

Uploaded new deb for Buster at Sourceforge

https://sourceforge.net/projects/dalle/files/dalle/dalle-1.14.03/

**Comment by EuriNaiz** [comment]
OMG!!!!!!! Muchisimas gracias, apenas vi las notificaciones lo descargué, el programa funciona perfectamente, ¡Gracias! de verdad, ¡gracias!.
