### ISSUE TITLE
Move all pages from sourceforge to github

### ISSUE THREAD

**Issue by albfernandez** [albfernandez/dalle#3]
Currently de development is done in github repo, but pages and other info are only in sourceforge pages.
Redirect sourceforge pages to new versions in github.

**Comment by EuriNaiz** [comment]
Quizás no es muy creativo de mi parte pero, he visto la plantilla [minimal](https://pages-themes.github.io/minimal/), la cual a mi parecer podría ser perfecta para la web actualizada de dalle, ¿te parece bien si hago una web con ella?

**Comment by albfernandez** [comment]
Hola
Agradezco mucho tu ofrecimiento. He creado el directorio ```docs```  en el repositorio para albergar la web visible en 
http://albfernandez.github.io/dalle/
Cuando lo tengas haz una pull request y no te olvides de añadierte en AUTHORS

Muchas gracias
